---
title: "Informal Rust Gamedev in 2024 Survey"
author: "Jan Hohenheim"
date: "2024-05-04"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependencies

```{r, message = F}
library(tidyverse)
library(glue)
library(ggthemes)
library(latex2exp)
library(glmnet)
library(MASS)
library(rstatix)
library(ordinal)
library(MASS)
library(DescTools)
library(wordcloud2) 
library(webshot)
library("htmlwidgets")
webshot::install_phantomjs(force = FALSE)

theme_set(theme_solarized_2())
palette <- function(n) {
  scale_color_solarized()$palette(n)[[n]]
}
```

## Data Wrangling

### Data Cleaning

```{r}
dat_raw <- read_csv("data_original.csv")
```

```{r}
dat <- dat_raw |>
  # Change names
  ## Timestamp
  rename_at(1, ~ "timestamp") |>
  ## On a scale of 1 to 5, how high is your excitement for the newsletter in its current form?
  rename_at(2, ~ "excitement") |>
  ## How would you change the amount of content per newsletter? (e.g. have 2 library updates instead of 5)
  rename_at(3, ~ "amount") |>
  ## How would you change the frequency of the newsletter?
  rename_at(4, ~ "frequency") |>
  ## How would you feel if some minor content of the newsletter was generated by an AI if the maintainers didn't get to it in time? This content would still be checked and edited by a human before release.
  rename_at(5, ~ "ai") |>
  ## The current tone of voice in the newsletter is...
  rename_at(6, ~ "tone") |>
  ## How often have you contributed to the newsletter before?
  rename_at(7, ~ "contributions") |>
  ## On a scale of 1-5, how easy is the current process for contributing to the newsletter? Leave this out if you've never interacted with this process.
  rename_at(8, ~ "ease") |>
  ## How do you usually get informed about a new edition of the newsletter?
  rename_at(9, ~ "informed") |>
  ## What about the newsletter do you like and wish to not be changed?
  rename_at(10, ~ "like") |>
  ## What is the most important thing to improve about the newsletter?
  rename_at(11, ~ "improve") |>
  ## Is there something else you would like to tell us?
  rename_at(12, ~ "comment") |>
  # Rename factors
  mutate(
    amount = fct_recode(amount, 
      less = "less content; keep only the most important news",
      leave = "leave it as-is",
      more = "more content; add sections for minor news",
      dont_care = "I don't care",
    ),
    frequency = fct_recode(frequency,
      weekly = "make it weekly",
      monthly = "leave it monthly",
      quarterly = "make it quarterly",
      dont_care = "I don't care",
    ),
    ai = fct_recode(ai,
      not_okay = "not okay at all",
      okay = "not ideal, but okay",
      good = "sounds like a good idea",
      love = "I love this",
      dont_care = "I don't care",
    ),
    tone = fct_recode(tone,
      too_formal = "too formal",
      just_right = "just right",
      too_casual = "too informal",
    ),
    contributions = fct_recode(contributions,
      "0" = "never",
      "1" = "once",
      "2-5" = "2-5 times",
      ">5" = "more than 5 times",
    ),
  ) |>
  mutate(
    informed = informed |>
      tolower() |>
      str_replace_all("this-week-in-rust", "informed_twir") |>
      str_replace_all("this week in rust", "informed_twir") |>
      str_replace_all("twitter / x", "informed_twitter") |>
      str_replace_all("mastodon", "informed_mastodon") |>
      str_replace_all("rss", "informed_rss") |>
      str_replace_all("reddit", "informed_reddit") |>
      str_replace_all("email subscription to some channel", "informed_email") |>
      str_replace_all("the official rust gamedev discord server", "informed_discord_main") |>
      str_replace_all("some other discord server", "informed_discord_other") |>
      str_replace_all("hacker news", "informed_hacker_news") |>
      str_replace_all("i visit the website every few week", "informed_website")
  )

# The following splits the "informed" column, 
# which contains factors concatenated by ;, 
# into multiple boolean columns
# Source: <https://stackoverflow.com/a/64412498/5903309>
informed <- unique(unlist(strsplit(dat$informed, ';'), recursive = FALSE))
informed <- informed[!is.na(informed)]

for (level in informed) {
  dat$newcol = rep(0)
  dat <- rename(dat, !!level := newcol)
  dat[grep(level, dat$informed), level] = 1
}

# Add options no one picked
dat$informed_lemmy <- 0
dat$informed_friends <- 0


dat <- dat |>
  dplyr::select(-informed) |>
  dplyr::select(-timestamp)

dat |> write_csv("data_cleaned.csv")
```

### Load Data

```{r}
dat <- read_csv("data_cleaned.csv") |>
  mutate(
    excitement = 
      as_factor(excitement) |> 
      fct_relevel("1", "2", "3", "4", "5"),
    amount = as_factor(amount),
    frequency = as_factor(frequency),
    ai = 
      as_factor(ai) |>
      fct_relevel("not_okay", "okay", "dont_care", "good", "love"),
    tone = as_factor(tone),
    contributions = 
      as_factor(contributions) |>
      fct_relevel("0", "1", "2-5", ">5"),
    ease = 
      as_factor(ease) |>
      fct_relevel("1", "2", "3", "4", "5"),
    informed_twir = as_factor(informed_twir),
    informed_twitter = as_factor(informed_twitter),
    informed_rss = as_factor(informed_rss),
    informed_reddit = as_factor(informed_reddit),
    informed_email = as_factor(informed_email),
    informed_discord_main = as_factor(informed_discord_main),
    informed_discord_other = as_factor(informed_discord_other),
    informed_hacker_news = as_factor(informed_hacker_news),
    informed_website = as_factor(informed_website),
    informed_mastodon = as_factor(informed_mastodon),
    informed_lemmy = as_factor(informed_lemmy),
    informed_friends = as_factor(informed_friends),
  )

dat |> summary()
dat |> head()
```

## Plots

### Excitement

```{r}
scale_values <- c(
  rgb(0, 255, 136, maxColorValue = 255),
  rgb(163, 244, 0, maxColorValue = 255),
  rgb(255, 211, 0, maxColorValue = 255),
  rgb(255, 172, 0, maxColorValue = 255),
  rgb(255, 147, 67, maxColorValue = 255)
)
```

```{r}
dat |> 
  count(excitement) |>
  ggplot(aes(x = excitement, y = n, fill = excitement)) +
  scale_fill_manual(values = scale_values |> rev()) +
  geom_col() +
  theme(legend.position = "none") +
  labs(
    title = "How high is your excitement for the newsletter in its current form?",
    y = "Count",
    x = "Excitement",
    fill = "Excitement"
  )
ggsave("excitement.png")
```

```{r}
dat |> 
  count(excitement) |>
  mutate(
    excitement = excitement |> 
      fct_reorder(
        as.numeric(excitement),
        .desc = TRUE
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = excitement)) +
  scale_fill_manual(values = scale_values) +
  geom_col() +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "How high is your excitement for the newsletter in its current form?",
    y = "Count",
    x = NULL,
    fill = "Excitement"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### Amount

```{r}
dat |> 
  mutate(
    amount = amount |> 
      fct_relevel("less", "leave", "dont_care", "more") |>
      fct_recode(
        "Less Content" = "less",
        "Leave as-is" = "leave",
        "More Content" = "more",
        "Don't Care" = "dont_care"
      )
  ) |>
  count(amount) |>
  ggplot(aes(x = amount, y = n)) +
  geom_bar(stat = 'identity', fill = palette(1)) +
  theme(legend.position = "none") +
  labs(
    title = "How would you change the amount of content per newsletter?",
    y = "Count",
    x = "Amount",
  ) 
ggsave("content_quantity.png")
```

```{r}
dat |> 
  filter(amount != "dont_care") |>
  count(amount) |>
  mutate(
    amount = amount |> 
      fct_relevel("more", "leave", "less") |>
      fct_recode(
        "Less Content" = "less",
        "Leave as-is" = "leave",
        "More Content" = "more",
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = amount)) +
  scale_fill_manual(values = c(palette(2), palette(1), palette(2))) +
  geom_bar(stat = 'identity') +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "How would you change the amount of content per newsletter?",
    y = "Count",
    x = NULL,
    fill = "Amount"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### Frequency

```{r}
dat |> 
  mutate(
    frequency = frequency |> 
      fct_relevel("weekly", "monthly", "dont_care", "quarterly") |>
      fct_recode(
        "Weekly" = "weekly",
        "Leave as-is" = "monthly",
        "Quarterly" = "quarterly",
        "Don't Care" = "dont_care"
      )
  ) |>
  count(frequency) |>
  ggplot(aes(x = frequency, y = n, fill = frequency)) +
  geom_bar(stat = 'identity', fill = palette(1)) +
  theme(legend.position = "none") +
  labs(
    title = "How would you change the frequency of the newsletter?",
    y = "Count",
    x = "Frequency",
  )

ggsave("frequency.png")
```


```{r}
dat |> 
  filter(frequency != "dont_care") |>
  count(frequency) |>
  mutate(
    frequency = frequency |> 
      fct_relevel("quarterly", "monthly", "weekly") |>
      fct_recode(
        "Weekly" = "weekly",
        "Leave as-is" = "monthly",
        "Quarterly" = "quarterly",
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = frequency)) +
  scale_fill_manual(values = c(palette(2), palette(1), palette(2))) +
  geom_bar(stat = 'identity') +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "How would you change the frequency of the newsletter?",
    y = "Count",
    x = NULL,
    fill = "Frequency"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### AI

```{r}
dat |> 
  mutate(
    ai = ai |> 
      fct_relevel("not_okay", "okay", "dont_care", "good", "love") |>
      fct_recode(
        "Not Okay" = "not_okay",
        "Okay" = "okay",
        "Good" = "good",
        "Love" = "love",
        "Don't Care" = "dont_care"
      )
  ) |>
  count(ai) |>
  ggplot(aes(x = ai, y = n, fill = ai)) +
  geom_bar(stat = 'identity') +
  theme(legend.position = "none") +
  scale_fill_manual(values = scale_values |> rev()) +
  labs(
    title = "How would you feel if some minor content of the newsletter\nwas generated by an AI?",
    y = "Count",
    x = "AI",
  )

ggsave("ai.png")
```

```{r}
dat |> 
  count(ai) |>
  mutate(
    ai = ai |> 
      fct_relevel("love", "good", "dont_care", "okay", "not_okay") |>
      fct_recode(
        "Not Okay" = "not_okay",
        "Okay" = "okay",
        "Good" = "good",
        "Love" = "love",
        "Don't Care" = "dont_care"
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = ai)) +
  scale_fill_manual(values = scale_values) +
  geom_bar(stat = 'identity') +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "How would you feel if some minor content of the newsletter\nwas generated by an AI?",
    y = "Count",
    x = NULL,
    fill = "AI"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### Tone

```{r}
dat |> 
  mutate(
    tone = tone |> 
      fct_relevel("too_formal", "just_right", "too_casual") |>
      fct_recode(
        "Too Formal" = "too_formal",
        "Just Right" = "just_right",
        "Too Casual" = "too_casual",
      )
  ) |>
  count(tone) |>
  ggplot(aes(x = tone, y = n, fill = tone)) +
  geom_bar(stat = 'identity') +
  theme(legend.position = "none") +
  scale_fill_manual(values = c(palette(2), palette(1), palette(2)))+
    labs(
    title = "The current tone of voice in the newsletter is...",
    y = "Count",
    x = "Tone",
  )

ggsave("tone.png")
```
```{r}
dat |> 
  count(tone) |>
  mutate(
    tone = tone |> 
      fct_relevel("too_casual", "just_right", "too_formal") |>
      fct_recode(
        "Too Formal" = "too_formal",
        "Just Right" = "just_right",
        "Too Casual" = "too_casual",
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = tone)) +
  scale_fill_manual(values = c(palette(2), palette(1), palette(2))) +
  geom_bar(stat = 'identity') +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "The current tone of voice in the newsletter is...",
    y = "Count",
    x = NULL,
    fill = "Tone"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### Contributions

```{r}
dat |> 
  count(contributions) |>
  mutate(
    contributions = contributions |> 
      fct_relevel("0", "1", "2-5", ">5") |>
      fct_recode(
        "Never" = "0",
        "Once" = "1",
        "2-5 Times" = "2-5",
        "More than 5 Times" = ">5",
      )
  ) |>
  ggplot(aes(x = contributions, y = n, fill = contributions)) +
  geom_bar(stat = 'identity') +
  theme(legend.position = "none") +
  scale_fill_manual(values = c(palette(1), palette(1), palette(1), palette(1))) +
  labs(
    title = "How often have you contributed to the newsletter before?",
    y = "Count",
    x = "Contributions",
  )

ggsave("contributions.png")
```

### Ease

```{r}
dat |> 
  filter(!is.na(ease)) |>
  count(ease) |>
  ggplot(aes(x = ease, y = n, fill = ease)) +
  geom_bar(stat = 'identity') +
  theme(legend.position = "none") +
  scale_fill_manual(values = scale_values |> rev()) +
  labs(
    title = "How easy is the current process for contributing to the newsletter?",
    y = "Count",
    x = "Ease",
  )

ggsave("ease.png")
```

```{r}
dat |> 
  filter(!is.na(ease)) |>
  count(ease) |>
  mutate(
    ease = ease |> 
      fct_reorder(
        as.numeric(ease),
        .desc = TRUE
      )
  ) |>
  ggplot(aes(x = 1, y = n, fill = ease)) +
  scale_fill_manual(values = scale_values) +
  geom_bar(stat = 'identity') +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  labs(
    title = "How easy is the current process for contributing to the newsletter?",
    y = "Count",
    x = NULL,
    fill = "Ease"
  ) +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) + 
  coord_flip()
```

### Informed

```{r}
dat |> 
  dplyr::select(starts_with("informed")) |>
  pivot_longer(cols = everything()) |>
  filter(value == 1) |>
  count(name) |>
  rbind(
    tibble(name = "informed_friends", n = 0),
    tibble(name = "informed_lemmy", n = 0)
  ) |>
  mutate(
    name = name |> 
      fct_recode(
        "X / Twitter" = "informed_twitter",
        "RSS" = "informed_rss",
        "Reddit" = "informed_reddit",
        "Email" = "informed_email",
        "Official Discord" = "informed_discord_main",
        "Other Discord" = "informed_discord_other",
        "Hacker News" = "informed_hacker_news",
        "Website" = "informed_website",
        "This Week in Rust" = "informed_twir",
        "Group Chat" = "informed_friends",
        "Lemmy" = "informed_lemmy",
        "Mastodon" = "informed_mastodon",
      ) |> 
      fct_relevel(c(
        "RSS", 
        "Official Discord", 
        "Reddit", 
        "Other Discord",
        "Mastodon", 
        "X / Twitter", 
        "This Week in Rust", 
        "Email", 
        "Hacker News", 
        "Website", 
        "Group Chat", 
        "Lemmy") |> rev())
  ) |>
  ggplot(aes(x = name, y = n)) +
  geom_bar(stat = 'identity', fill = palette(1)) +
  theme(legend.position = "none") +
  labs(
    title = "How do you usually get informed about\na new edition of the newsletter?",
    y = "Count",
    x = "Informed",
  ) +
  coord_flip()

ggsave("informed.png")
```


### Comments

```{r}
clean_words <- function(text) {
  text |> 
    str_to_lower() |> 
    str_remove_all("[[:punct:]]") |> 
    str_remove_all("\\d+") |> 
    str_replace_all("\\s+", " ") |>
    str_split(" ") |>
    unlist() |> 
    table() |>
    as.data.frame() |>
    arrange(desc(Freq)) |>
    rename(word = Var1, freq = Freq) |>
    mutate(word = as.character(word)) |>
    # common words
    filter(!word %in% c("i", "a", "the", "to", "and", "of", "in", "for", "is", "it", "on", "that", "with", "from", "this", "have", "more", "what", "about", "would", "like", "your", "just", "some", "other", "also", "there", "them", "they", "their", "when", "will", "were", "were", "which", "or", "as", "has", "if", "am", "at", "all", "by", "an", "its", "isnt", "wouldnt", "+", "too", "did", "be", "^^", "so", "do", "are", "but")) |>
    # boring results
    filter(!word %in% c("newsletter", "rust", "game", "games"))
}

plot_words <- function(text, filename, pixels) {
  graph <- text |> 
    clean_words() |>
    wordcloud2()
  # See <https://stackoverflow.com/a/47850987/5903309>
  saveWidget(graph, "tmp.html", selfcontained = F)
  webshot("tmp.html", filename, delay = 5, vwidth = pixels, vheight = pixels)
}
```

```{r}
dat$like |> plot_words("like.png", 1500)
dat$improve |> plot_words("improve.png", 1700)
dat$comment |> plot_words("comment.png", 1500)
```


## Analysis

### Excitement

```{r}
dat_ <- dat$excitement |> as.numeric()
mean_ <- dat_ |> mean()
sd_ <- dat_ |> sd()
se_ <- sd_ / sqrt(length(dat_))
ci_ <- t.test(dat_)$conf.int
median_ <- dat_ |> median()
"mean: {mean_}" |> glue()
"standard deviation: {sd_}" |> glue()
"standard error: {se_}" |> glue()
"95% confidence interval: [{ci_[1]}, {ci_[2]}]" |> glue()
"median: {median_}" |> glue()

t.test(dat_ - 3)
```

### Amount

```{r}
dat |> 
  count(amount) |>
  mutate(
    percentage = n / sum(n) * 100
  )

```

### Frequency

```{r}
# percentages for each factor
dat |> 
  count(frequency) |>
  mutate(
    percentage = n / sum(n) * 100
  )

dat_ <- dat |> 
  filter(frequency != "dont_care") |>
  pull(frequency) |>
  as.numeric()
t.test(dat_ - 1.5)
```

### AI

```{r}
dat |> 
  count(ai) |>
  mutate(
    percentage = n / sum(n) * 100
  )

dat_ <- dat$ai |> as.numeric()
mean_ <- dat_ |> mean()
sd_ <- dat_ |> sd()
se_ <- sd_ / sqrt(length(dat_))
ci_ <- t.test(dat_)$conf.int
median_ <- dat_ |> median()
"mean: {mean_}" |> glue()
"standard deviation: {sd_}" |> glue()
"standard error: {se_}" |> glue()
"95% confidence interval: [{ci_[1]}, {ci_[2]}]" |> glue()
"median: {median_}" |> glue()

t.test(dat_ - 3)
```

### Tone

```{r}
dat |> 
  count(tone) |>
  mutate(
    percentage = n / sum(n) * 100
  )
```

### Contributions

```{r}
dat |> 
  count(contributions) |>
  mutate(
    percentage = n / sum(n) * 100
  )
```

### Ease

```{r}
dat_ <- dat$ease[!is.na(dat$ease)] |> as.numeric()
mean_ <- dat_ |> mean()
sd_ <- dat_ |> sd()
se_ <- sd_ / sqrt(length(dat_))
ci_ <- t.test(dat_)$conf.int
median_ <- dat_ |> median()
"mean: {mean_}" |> glue()
"standard deviation: {sd_}" |> glue()
"standard error: {se_}" |> glue()
"95% confidence interval: [{ci_[1]}, {ci_[2]}]" |> glue()
"median: {median_}" |> glue()

t.test(dat_ - 3)
```

### Informed

```{r}
dat |> 
  dplyr::select(starts_with("informed")) |>
  pivot_longer(cols = everything()) |>
  filter(value == 1) |>
  count(name) |>
  mutate(
    percentage = n / sum(n) * 100
  ) |>
  arrange(desc(n))
```

### Correlation

```{r}
# plot excitement by contributions
dat |> 
  ggplot(aes(x = contributions, y = excitement)) +
  geom_point() +
  geom_jitter() +
  labs(
    title = "Excitement by Contributions",
    x = "Contributions",
    y = "Excitement"
  )

ggsave("excitement_contributions.png")

# plot ai by contributions
dat |> 
  ggplot(aes(x = contributions, y = ai)) +
  geom_point() +
  geom_jitter() +
  labs(
    title = "AI by Contributions",
    x = "Contributions",
    y = "AI"
  )

ggsave("ai_contributions.png")

# plot ease by contributions
dat |> 
  filter(!is.na(ease)) |>
  ggplot(aes(x = contributions, y = ease)) +
  geom_point() +
  geom_jitter() +
  labs(
    title = "Ease by Contributions",
    x = "Contributions",
    y = "Ease"
  )

ggsave("ease_contributions.png")
```

```{r}
JonckheereTerpstraTest(
  excitement ~ contributions, 
  dat, 
  alternative = "decreasing", 
  nperm = 1000,
  exact = FALSE
)

JonckheereTerpstraTest(
  ai ~ contributions, 
  dat, 
  alternative = "two.sided", 
  nperm = 1000,
  exact = FALSE
)

JonckheereTerpstraTest(
  ease ~ contributions, 
  dat |> filter(!is.na(ease)), 
  alternative = "two.sided", 
  nperm = 1000,
  exact = FALSE
)
```
